app            = "lumen"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  RAILS_ENV           = "production"
  RAILS_LOG_TO_STDOUT = "true"
  PORT                = "3000"

[[services]]
  internal_port = 3000
  protocol      = "tcp"

  [[services.ports]]
    handlers    = ["http"]
    port        = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port     = 443

  [services.concurrency]
    type       = "connections"
    hard_limit = 100
    soft_limit = 80

[[vm]]
  size   = "shared-cpu-1x"
  memory = "512mb"
